<template>
  <div class="post-truck">
    <div class="container">
      <h1 class="h1">POST Trucks</h1>
    </div>
    <post-load :allData="passedData">
      <template v-slot:iconOfNew>
        <img :src="passedData.iconOfNew" alt="" />
      </template>
    </post-load>

    <posted-load
      v-for="value in postedLoads"
      :key="value"
      :postedData="value"
    ></posted-load>

    <load-filter :numOfResults="numOfResults" />

    <searched-loads :filteredData="filteredData" />
  </div>
</template>

<script>
import PostLoad from "../components/PostLoad.vue";
import PostedLoad from "../components/PostedLoad.vue";
import LoadFilter from "../components/LoadFilter.vue";
import SearchedLoads from "../components/SearchedLoads.vue";

import download from "../assets/download.png";
import truck from "../assets/truck.png";
import dropdown from "../assets/dropdn.png";
import calendar from "../assets/calen.png";
import lamp from "../assets/lamp.png";
import bell from "../assets/bell.png";
import star from "../assets/star.png";
import stack from "../assets/stack.png";

export default {
  components: {
    PostLoad,
    PostedLoad,
    LoadFilter,
    SearchedLoads,
  },
  data() {
    return {
      passedData: {
        iconOfNew: truck,
        iconOfDownload: download,
        dropdownIcon: dropdown,
        lamp,
        title: "NEW POST TRUCK",
        alert: "Alert",
        info: [
          {
            id: 1,
            title: "Keep",
            value: "",
          },
          {
            id: 2,
            title: "Age",
            value: "",
          },
          {
            id: 3,
            title: "Status",
            value: "",
          },
          {
            id: 4,
            title: "Pickup",
            value: "12/31",
            valueMore: "Noon and 2pm ",
            icon: dropdown,
            iconSecond: calendar,
          },
          {
            id: 5,
            title: "Owner",
            value: "",
          },
          {
            id: 6,
            title: "Origin",
            value: "City,ST",
          },
          {
            id: 7,
            title: "Destination",
            value: "City,ST",
          },
          {
            id: 8,
            title: "Dock Hours",
            value: "3p-5p",
          },
          {
            id: 9,
            title: "Truck",
            value: "",
          },
          {
            id: 10,
            title: "F/P",
            value: "Full",
            icon: dropdown,
          },
          {
            id: 11,
            title: "Length",
            value: "999",
            icon: "",
          },
          {
            id: 12,
            title: "Weight",
            value: "999,999",
          },
          {
            id: 13,
            title: "Offer Rate($)",
            value: "999",
            valueMore: "Flat",
            icon: dropdown,
          },
        ],
        contacts: {
          required: true,
        },
        comments: {
          required: true,
        },
        button: {
          required: true,
          text: "POST",
        },
        search: {
          required: false,
        },
      },

      postedLoads: {
        postedData: {
          indicator: {
            on: false,
            text: "off",
          },
          bell,
          star,
          postedTime: "00:10",
          status: "Posted",
          date: "12/31",
          daytime: "AM",
          from: "Anew,AH",
          to: "Boldumsaz,DZ",
          dockHours: "1/2 8am to 12 pm",
          truck: "VAN",
          filling: "Full",
          length: "48 ft",
          weight: "48,000 lb",
          offerRate: "$230",
          refId: 123456,
          contact: "993(62)000000",
          miles: "999",
          comment1: "Call Eric x555",
          comment2: "102* wide is rqd",
          commodity: "Electronics ",
          alertId: "check2",
        },
        postedData2: {
          indicator: {
            on: true,
            text: "on",
          },
          bell,
          star,
          postedTime: "00:10",
          status: "Posted",
          date: "12/31",
          daytime: "AM",
          from: "Anew,AH",
          to: "Boldumsaz,DZ",
          dockHours: "1/2 8am to 12 pm",
          truck: "VAN",
          filling: "Pa-l",
          length: "48 ft",
          weight: "48,000 lb",
          offerRate: "$230",
          refId: 123456,
          contact: "993(62)000000",
          miles: "999",
          comment1: "Call Eric x555",
          comment2: "102* wide is rqd",
          commodity: "Electronics ",
          alertId: "check3",
        },
        postedData3: {
          indicator: {
            on: true,
            text: "on",
          },
          bell,
          star,
          postedTime: "00:10",
          status: "Posted",
          date: "12/31",
          daytime: "AM",
          from: "Anew,AH",
          to: "Boldumsaz,DZ",
          dockHours: "1/2 8am to 12 pm",
          truck: "VAN",
          filling: "Full",
          length: "48 ft",
          weight: "50,000 lb",
          offerRate: "$230",
          refId: 123456,
          contact: "993(62)000000",
          miles: "999",
          comment1: "Call Eric x555",
          comment2: "102* wide is rqd",
          commodity: "Electronics ",
          alertId: "check4",
        },
      },

      numOfResults: 0,

      filteredData: {
        dropdownIcon: dropdown,
        stackIcon: stack,
        filters: [
          {
            id: 1,
            title: "Age",
            icon: dropdown,
          },
          {
            id: 2,
            title: "Avial",
          },
          {
            id: 3,
            title: "Truck",
          },
          {
            id: 4,
            title: "F/P",
          },
          {
            id: 5,
            title: "DH-O",
          },
          {
            id: 6,
            title: "Origin",
          },
          {
            id: 7,
            title: "Trip",
          },
          {
            id: 8,
            title: "Destination",
          },
          {
            id: 9,
            title: "DH-D",
          },
          {
            id: 10,
            title: "Company",
          },
          {
            id: 11,
            title: "Contact",
          },
          {
            id: 12,
            title: "Length",
          },
          {
            id: 13,
            title: "Weight",
          },
          {
            id: 14,
            title: "Home",
          },
        ],

        values: [
          {
            age: "00:10",
            avial: "12/31",
            truck: "V",
            fP: "F",
            dHO: "999",
            origin: "Anew,AH",
            trip: "-",
            destination: "Anywhere",
            dHD: "-",
            company: "Load triller",
            contact: "993(62)000000",
            length: "48 ft",
            weight: "50,000lb",
            home: "AG",
          },
          {
            age: "00:10",
            avial: "12/31",
            truck: "V",
            fP: "F",
            dHO: "999",
            origin: "Anew,AH",
            trip: "-",
            destination: "Anywhere",
            dHD: "-",
            company: "Load triller",
            contact: "993(62)000000",
            length: "48 ft",
            weight: "50,000lb",
            home: "AG",
          },
          {
            age: "00:10",
            avial: "12/31",
            truck: "V",
            fP: "F",
            dHO: "999",
            origin: "Anew,AH",
            trip: "-",
            destination: "Anywhere",
            dHD: "-",
            company: "Load triller",
            contact: "993(62)000000",
            length: "48 ft",
            weight: "50,000lb",
            home: "AG",
          },
          {
            age: "00:10",
            avial: "12/31",
            truck: "V",
            fP: "F",
            dHO: "999",
            origin: "Anew,AH",
            trip: "-",
            destination: "Anywhere",
            dHD: "-",
            company: "Load triller",
            contact: "993(62)000000",
            length: "48 ft",
            weight: "50,000lb",
            home: "AG",
          },
          {
            age: "00:10",
            avial: "12/31",
            truck: "V",
            fP: "F",
            dHO: "999",
            origin: "Anew,AH",
            trip: "-",
            destination: "Anywhere",
            dHD: "-",
            company: "Load triller",
            contact: "993(62)000000",
            length: "48 ft",
            weight: "50,000lb",
            home: "AG",
          },
          {
            age: "00:10",
            avial: "12/31",
            truck: "V",
            fP: "F",
            dHO: "999",
            origin: "Anew,AH",
            trip: "-",
            destination: "Anywhere",
            dHD: "-",
            company: "Load triller",
            contact: "993(62)000000",
            length: "48 ft",
            weight: "50,000lb",
            home: "AG",
          },
          {
            age: "00:10",
            avial: "12/31",
            truck: "V",
            fP: "F",
            dHO: "999",
            origin: "Anew,AH",
            trip: "-",
            destination: "Anywhere",
            dHD: "-",
            company: "Load triller",
            contact: "993(62)000000",
            length: "48 ft",
            weight: "50,000lb",
            home: "AG",
          },
          {
            age: "00:10",
            avial: "12/31",
            truck: "V",
            fP: "F",
            dHO: "999",
            origin: "Anew,AH",
            trip: "-",
            destination: "Anywhere",
            dHD: "-",
            company: "Load triller",
            contact: "993(62)000000",
            length: "48 ft",
            weight: "50,000lb",
            home: "AG",
          },
          {
            age: "00:10",
            avial: "12/31",
            truck: "V",
            fP: "F",
            dHO: "999",
            origin: "Anew,AH",
            trip: "-",
            destination: "Anywhere",
            dHD: "-",
            company: "Load triller",
            contact: "993(62)000000",
            length: "48 ft",
            weight: "50,000lb",
            home: "AG",
          },
          {
            age: "00:10",
            avial: "12/31",
            truck: "V",
            fP: "F",
            dHO: "999",
            origin: "Anew,AH",
            trip: "-",
            destination: "Anywhere",
            dHD: "-",
            company: "Load triller",
            contact: "993(62)000000",
            length: "48 ft",
            weight: "50,000lb",
            home: "AG",
          },
          {
            age: "00:10",
            avial: "12/31",
            truck: "V",
            fP: "F",
            dHO: "999",
            origin: "Anew,AH",
            trip: "-",
            destination: "Anywhere",
            dHD: "-",
            company: "Load triller",
            contact: "993(62)000000",
            length: "48 ft",
            weight: "50,000lb",
            home: "AG",
          },
          {
            age: "00:10",
            avial: "12/31",
            truck: "V",
            fP: "F",
            dHO: "999",
            origin: "Anew,AH",
            trip: "-",
            destination: "Anywhere",
            dHD: "-",
            company: "Load triller",
            contact: "993(62)000000",
            length: "48 ft",
            weight: "50,000lb",
            home: "AG",
          },
          {
            age: "00:10",
            avial: "12/31",
            truck: "V",
            fP: "F",
            dHO: "999",
            origin: "Anew,AH",
            trip: "-",
            destination: "Anywhere",
            dHD: "-",
            company: "Load triller",
            contact: "993(62)000000",
            length: "48 ft",
            weight: "50,000lb",
            home: "AG",
          },
          {
            age: "00:10",
            avial: "12/31",
            truck: "V",
            fP: "F",
            dHO: "999",
            origin: "Anew,AH",
            trip: "-",
            destination: "Anywhere",
            dHD: "-",
            company: "Load triller",
            contact: "993(62)000000",
            length: "48 ft",
            weight: "50,000lb",
            home: "AG",
          },
          {
            age: "00:10",
            avial: "12/31",
            truck: "V",
            fP: "F",
            dHO: "999",
            origin: "Anew,AH",
            trip: "-",
            destination: "Anywhere",
            dHD: "-",
            company: "Load triller",
            contact: "993(62)000000",
            length: "48 ft",
            weight: "50,000lb",
            home: "AG",
          },
          {
            age: "00:10",
            avial: "12/31",
            truck: "V",
            fP: "F",
            dHO: "999",
            origin: "Anew,AH",
            trip: "-",
            destination: "Anywhere",
            dHD: "-",
            company: "Load triller",
            contact: "993(62)000000",
            length: "48 ft",
            weight: "50,000lb",
            home: "AG",
          },
          {
            age: "00:10",
            avial: "12/31",
            truck: "V",
            fP: "F",
            dHO: "999",
            origin: "Anew,AH",
            trip: "-",
            destination: "Anywhere",
            dHD: "-",
            company: "Load triller",
            contact: "993(62)000000",
            length: "48 ft",
            weight: "50,000lb",
            home: "AG",
          },
          {
            age: "00:10",
            avial: "12/31",
            truck: "V",
            fP: "F",
            dHO: "999",
            origin: "Anew,AH",
            trip: "-",
            destination: "Anywhere",
            dHD: "-",
            company: "Load triller",
            contact: "993(62)000000",
            length: "48 ft",
            weight: "50,000lb",
            home: "AG",
          },
          {
            age: "00:10",
            avial: "12/31",
            truck: "V",
            fP: "F",
            dHO: "999",
            origin: "Anew,AH",
            trip: "-",
            destination: "Anywhere",
            dHD: "-",
            company: "Load triller",
            contact: "993(62)000000",
            length: "48 ft",
            weight: "50,000lb",
            home: "AG",
          },
          {
            age: "00:10",
            avial: "12/31",
            truck: "V",
            fP: "F",
            dHO: "999",
            origin: "Anew,AH",
            trip: "-",
            destination: "Anywhere",
            dHD: "-",
            company: "Load triller",
            contact: "993(62)000000",
            length: "48 ft",
            weight: "50,000lb",
            home: "AG",
          },
          {
            age: "00:10",
            avial: "12/31",
            truck: "V",
            fP: "F",
            dHO: "999",
            origin: "Anew,AH",
            trip: "-",
            destination: "Anywhere",
            dHD: "-",
            company: "Load triller",
            contact: "993(62)000000",
            length: "48 ft",
            weight: "50,000lb",
            home: "AG",
          },
          {
            age: "00:10",
            avial: "12/31",
            truck: "V",
            fP: "F",
            dHO: "999",
            origin: "Anew,AH",
            trip: "-",
            destination: "Anywhere",
            dHD: "-",
            company: "Load triller",
            contact: "993(62)000000",
            length: "48 ft",
            weight: "50,000lb",
            home: "AG",
          },
          {
            age: "00:10",
            avial: "12/31",
            truck: "V",
            fP: "F",
            dHO: "999",
            origin: "Anew,AH",
            trip: "-",
            destination: "Anywhere",
            dHD: "-",
            company: "Load triller",
            contact: "993(62)000000",
            length: "48 ft",
            weight: "50,000lb",
            home: "AG",
          },
        ],
      },
    };
  },
};
</script>

<style lang="scss" scoped>
.post-truck {
  .container {
    padding-top: 30vh;
  }
}
</style>
